<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <UseWPF>true</UseWPF>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AssemblyName>charlotte-gui</AssemblyName>
        <RootNamespace>MonsieurVerite</RootNamespace>
        <Product>charlotte</Product>
        <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
        <EnableSingleFileAnalyzer>true</EnableSingleFileAnalyzer>
    </PropertyGroup>

    <PropertyGroup Condition="'$(_IsPublishing)' == 'true'">
        <RuntimeIdentifier>win-x64</RuntimeIdentifier>
        <SelfContained>true</SelfContained>
        <PublishSingleFile>true</PublishSingleFile>
        <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
        <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
        <DebugType>none</DebugType>
        <PublishDocumentationFile>false</PublishDocumentationFile>
        <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
        <RestoreLockedMode>true</RestoreLockedMode>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
        <PackageReference Include="Microsoft.NET.ILLink.Tasks" Version="10.0.12" PrivateAssets="all" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="MonsieurVerite.Tests" />
    </ItemGroup>

</Project>
